framework:
    default_locale: cs
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - en
        providers:

when@test:
    framework:
        default_locale: cs