twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        app_site_name: '%app_site_name%'
        app_menu_theme: '%app_menu_theme%'

when@test:
    twig:
        strict_variables: true
