twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '_fragment/_form_theme/_custom_layout.html.twig'

when@test:
    twig:
        strict_variables: true
