twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '_fragment/_form_theme/_custom_layout.html.twig'

    globals:
        phone_number_format: '%app.phone_number_format%'
        date_format: '%app.date_format%'
        date_time_format: '%app.date_time_format%'
        sale_camper_siblings_enabled: '%app.sale_camper_siblings%'

when@test:
    twig:
        strict_variables: true
