twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
        - '_fragment/_form_theme/_custom_layout.html.twig'
        - '_fragment/_form_theme/_admin_whole_forms.html.twig'
        - '_fragment/_form_theme/_user_whole_forms.html.twig'

    globals:
        tax: '%app.tax%'
        currency: '%app.currency%'
        phone_number_format: '%app.phone_number_format%'
        date_format: '%app.date_format%'
        date_time_format: '%app.date_time_format%'
        national_identifier_enabled: '%app.national_identifier%'

when@test:
    twig:
        strict_variables: true
