twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '_fragment/_form_theme/_custom_layout.html.twig'
        - '_fragment/_form_theme/_common_whole_forms.html.twig'
        - '_fragment/_form_theme/_admin_whole_forms.html.twig'
        - '_fragment/_form_theme/_user_whole_forms.html.twig'

    globals:
        company_email: '%app.email%'
        company_name: '%app.company_name%'
        company_structure: '%app.company_structure%'
        company_cin: '%app.company_cin%'
        company_vat_id: '%app.company_vat_id%'
        company_extra_business_info: '%app.company_extra_business_info%'
        company_bank_account: '%app.company_bank_account%'
        company_phone_number: '%app.company_phone_number%'
        company_address_street: '%app.company_address_street%'
        company_address_town: '%app.company_address_town%'
        company_address_zip: '%app.company_address_zip%'
        company_address_country: '%app.company_address_country%'
        company_social_media: '%app.company_social_media%'
        company_payments_and_security_icons: '%app.company_payments_and_security_icons%'

        tax: '%app.tax%'
        currency: '%app.currency%'
        phone_number_format: '%app.phone_number_format%'
        date_format: '%app.date_format%'
        date_time_format: '%app.date_time_format%'
        national_identifier_enabled: '%app.national_identifier%'
        social_login_services: '%app.social_login_services%'
        themes: '%app.themes%'
        google_tag_manager_id: '%env(GOOGLE_TAG_MANAGER_ID)%'
        enabled_cookie_consents: '%app.enabled_cookie_consents%'
        no_image_content_path: '%app.no_image_content_path%'

        post_param_cookie_consent_grant_all: '%app.post_param_cookie_consent_grant_all%'
        post_param_cookie_consent_deny_all: '%app.post_param_cookie_consent_deny_all%'
        post_param_cookie_consent_grant_preferences: '%app.post_param_cookie_consent_grant_preferences%'
        post_param_cookie_consent_preferences: '%app.post_param_cookie_consent_preferences%'

        seo_description: '%app.seo_description%'
        seo_author: '%app.seo_author%'

when@test:
    twig:
        strict_variables: true
