<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240310190456 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE application (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_date_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', payment_method_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', simple_id VARCHAR(6) NOT NULL, invoice_number INT NOT NULL, email VARCHAR(180) NOT NULL, name_first VARCHAR(255) NOT NULL, name_last VARCHAR(255) NOT NULL, street VARCHAR(255) NOT NULL, town VARCHAR(255) NOT NULL, zip VARCHAR(11) NOT NULL, country VARCHAR(2) NOT NULL, business_name VARCHAR(255) DEFAULT NULL, business_cin VARCHAR(32) DEFAULT NULL, business_vat_id VARCHAR(32) DEFAULT NULL, note VARCHAR(1000) DEFAULT NULL, customer_channel VARCHAR(255) DEFAULT NULL, customer_channel_other VARCHAR(255) DEFAULT NULL, is_draft TINYINT(1) NOT NULL, is_accepted TINYINT(1) DEFAULT NULL, camp_name VARCHAR(255) NOT NULL, camp_date_description VARCHAR(2000) DEFAULT NULL, payment_method_label VARCHAR(255) DEFAULT NULL, deposit DOUBLE PRECISION NOT NULL, price_without_deposit DOUBLE PRECISION NOT NULL, deposit_until DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', currency VARCHAR(3) NOT NULL, tax DOUBLE PRECISION NOT NULL, discount_recurring_campers_config LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', discount_siblings_config LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', discount_siblings_interval_from INT DEFAULT NULL, discount_siblings_interval_to INT DEFAULT NULL, is_eu_business_data_enabled TINYINT(1) NOT NULL, is_national_identifier_enabled TINYINT(1) NOT NULL, is_email_mandatory TINYINT(1) NOT NULL, is_phone_number_mandatory TINYINT(1) NOT NULL, is_purchasable_items_individual_mode TINYINT(1) NOT NULL, completed_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', camp_date_start_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', camp_date_end_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_A45BDDC1C8FAF195 (simple_id), UNIQUE INDEX UNIQ_A45BDDC12DA68207 (invoice_number), INDEX IDX_A45BDDC1C8047505 (camp_date_id), INDEX IDX_A45BDDC1A76ED395 (user_id), INDEX IDX_A45BDDC15AA1164F (payment_method_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_attachment (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', application_camper_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', label VARCHAR(255) NOT NULL, help VARCHAR(255) DEFAULT NULL, max_size DOUBLE PRECISION NOT NULL, required_type VARCHAR(16) NOT NULL, extensions LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', extension VARCHAR(255) DEFAULT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_EDCE8573E030ACD (application_id), INDEX IDX_EDCE857F300DF07 (application_camper_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_camper (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name_first VARCHAR(255) NOT NULL, name_last VARCHAR(255) NOT NULL, gender VARCHAR(1) NOT NULL, priority INT NOT NULL, born_at DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', national_identifier VARCHAR(255) DEFAULT NULL, dietary_restrictions VARCHAR(1000) DEFAULT NULL, health_restrictions VARCHAR(1000) DEFAULT NULL, medication VARCHAR(1000) DEFAULT NULL, trips_in_the_past INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_10FF46133E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_contact (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name_first VARCHAR(255) NOT NULL, name_last VARCHAR(255) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone_number VARCHAR(35) DEFAULT NULL COMMENT \'(DC2Type:phone_number)\', priority INT NOT NULL, role VARCHAR(32) NOT NULL, role_other VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A7DCE30B3E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_form_field_value (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', application_camper_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', type VARCHAR(32) NOT NULL, label VARCHAR(255) NOT NULL, options LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', is_required TINYINT(1) NOT NULL, help VARCHAR(255) DEFAULT NULL, priority INT NOT NULL, value LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_922E73113E030ACD (application_id), INDEX IDX_922E7311F300DF07 (application_camper_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_payment (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_payment_state_config_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', amount DOUBLE PRECISION NOT NULL, type VARCHAR(16) NOT NULL, state VARCHAR(255) NOT NULL, is_online TINYINT(1) NOT NULL, external_id VARCHAR(255) DEFAULT NULL, external_url VARCHAR(1000) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8696813E9F75D7B0 (external_id), UNIQUE INDEX UNIQ_8696813E545CEB66 (external_url), INDEX IDX_8696813E2AE7DEAB (application_payment_state_config_id), INDEX IDX_8696813E3E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_payment_state_config (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', states LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', paid_states LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', cancelled_states LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', refunded_states LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', pending_states LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', valid_state_changes LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_purchasable_item (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', purchasable_item_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', application_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', label VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, max_amount INT NOT NULL, description VARCHAR(2000) DEFAULT NULL, valid_variant_values LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', priority INT NOT NULL, is_global TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_6343508D16B4E87 (purchasable_item_id), INDEX IDX_63435083E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_purchasable_item_instance (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_camper_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', application_purchasable_item_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', chosen_variant_values LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', amount INT NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_907069E3F300DF07 (application_camper_id), INDEX IDX_907069E3EBD7A28D (application_purchasable_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_trip_location_path (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', application_camper_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', is_there TINYINT(1) NOT NULL, locations LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', location LONGTEXT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B334885F300DF07 (application_camper_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE attachment_config (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, max_size DOUBLE PRECISION NOT NULL, required_type VARCHAR(16) NOT NULL, help VARCHAR(255) DEFAULT NULL, is_global TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_968E294E5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE attachment_config_file_extension (attachment_config_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', file_extension_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_50153545520354A0 (attachment_config_id), INDEX IDX_50153545AB8C6E61 (file_extension_id), PRIMARY KEY(attachment_config_id, file_extension_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_category_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, url_name VARCHAR(255) NOT NULL, age_min INT NOT NULL, age_max INT NOT NULL, street VARCHAR(255) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, zip VARCHAR(11) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, is_featured TINYINT(1) NOT NULL, is_hidden TINYINT(1) NOT NULL, description_short VARCHAR(160) DEFAULT NULL, description_long VARCHAR(5000) DEFAULT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_C19442304077B7BE (url_name), INDEX IDX_C1944230B10A86AE (camp_category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_category (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', parent_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, url_name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_AC36C6DD727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_date (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', discount_config_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', trip_location_path_there_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', trip_location_path_back_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', start_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', end_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', deposit_until DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', deposit DOUBLE PRECISION NOT NULL, price_without_deposit DOUBLE PRECISION NOT NULL, capacity INT NOT NULL, is_open_above_capacity TINYINT(1) NOT NULL, is_closed TINYINT(1) NOT NULL, is_hidden TINYINT(1) NOT NULL, description VARCHAR(2000) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4F7C997277075ABB (camp_id), INDEX IDX_4F7C997244018E7E (discount_config_id), INDEX IDX_4F7C997263DD4162 (trip_location_path_there_id), INDEX IDX_4F7C99728B465358 (trip_location_path_back_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_date_attachment_config (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_date_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', attachment_config_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_BCCB6E1CC8047505 (camp_date_id), INDEX IDX_BCCB6E1C520354A0 (attachment_config_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_date_form_field (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_date_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', form_field_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_C623B972C8047505 (camp_date_id), INDEX IDX_C623B972F50D82F4 (form_field_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_date_purchasable_item (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_date_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', purchasable_item_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_7FCDDE3CC8047505 (camp_date_id), INDEX IDX_7FCDDE3CD16B4E87 (purchasable_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_date_user (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_date_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', can_update_applications_state TINYINT(1) NOT NULL, can_update_applications TINYINT(1) NOT NULL, can_update_application_payments TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_B9E6792DC8047505 (camp_date_id), INDEX IDX_B9E6792DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camp_image (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', camp_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', priority INT NOT NULL, extension VARCHAR(8) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_CB036EC377075ABB (camp_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE camper (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name_first VARCHAR(255) NOT NULL, name_last VARCHAR(255) NOT NULL, gender VARCHAR(1) NOT NULL, born_at DATE NOT NULL COMMENT \'(DC2Type:date_immutable)\', national_identifier VARCHAR(255) DEFAULT NULL, dietary_restrictions VARCHAR(1000) DEFAULT NULL, health_restrictions VARCHAR(1000) DEFAULT NULL, medication VARCHAR(1000) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_A0CC4AD6A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE contact (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name_first VARCHAR(255) NOT NULL, name_last VARCHAR(255) NOT NULL, email VARCHAR(180) DEFAULT NULL, phone_number VARCHAR(35) DEFAULT NULL COMMENT \'(DC2Type:phone_number)\', role VARCHAR(32) NOT NULL, role_other VARCHAR(255) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_4C62E638A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE discount_config (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, recurring_campers_config LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', siblings_config LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_BACA03435E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE file_extension (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', extension VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_11B882019FB73D77 (extension), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE form_field (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, label VARCHAR(255) NOT NULL, options LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', is_required TINYINT(1) NOT NULL, help VARCHAR(255) DEFAULT NULL, is_global TINYINT(1) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_D8B2E19B5E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE payment_method (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, is_online TINYINT(1) NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_7B61A1F65E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permission (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', permission_group_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(64) NOT NULL, label VARCHAR(64) NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_E04992AA5E237E06 (name), INDEX IDX_E04992AAB6C0CF1 (permission_group_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE permission_group (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(64) NOT NULL, label VARCHAR(64) NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_BB4729B65E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchasable_item (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, label VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, max_amount INT NOT NULL, is_global TINYINT(1) NOT NULL, image_extension VARCHAR(8) DEFAULT NULL, description VARCHAR(2000) DEFAULT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_55A118C75E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchasable_item_variant (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', purchasable_item_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_83EA40A75E237E06 (name), INDEX IDX_83EA40A7D16B4E87 (purchasable_item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE purchasable_item_variant_value (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', purchasable_item_variant_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_9114C9325E237E06 (name), INDEX IDX_9114C932AD0CA35 (purchasable_item_variant_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', label VARCHAR(64) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_57698A6AEA750E8 (label), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE role_permission (role_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', permission_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', INDEX IDX_6F7DF886D60322AC (role_id), INDEX IDX_6F7DF886FED90CCA (permission_id), PRIMARY KEY(role_id, permission_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trip_location (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', trip_location_path_id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, price DOUBLE PRECISION NOT NULL, priority INT NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_F6CFBADB559CC42E (trip_location_path_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE trip_location_path (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', name VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_28E8CE45E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', role_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', email VARCHAR(180) NOT NULL, password VARCHAR(255) DEFAULT NULL, name_first VARCHAR(255) DEFAULT NULL, name_last VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, town VARCHAR(255) DEFAULT NULL, zip VARCHAR(11) DEFAULT NULL, country VARCHAR(2) DEFAULT NULL, business_name VARCHAR(255) DEFAULT NULL, business_cin VARCHAR(32) DEFAULT NULL, business_vat_id VARCHAR(32) DEFAULT NULL, born_at DATE DEFAULT NULL COMMENT \'(DC2Type:date_immutable)\', bio VARCHAR(2000) DEFAULT NULL, image_extension VARCHAR(8) DEFAULT NULL, url_name VARCHAR(255) DEFAULT NULL, guide_priority INT NOT NULL, last_active_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D6494077B7BE (url_name), INDEX IDX_8D93D649D60322AC (role_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_password_change (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', user_id BINARY(16) DEFAULT NULL COMMENT \'(DC2Type:uuid)\', expire_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', state VARCHAR(32) NOT NULL, selector VARCHAR(32) NOT NULL, verifier VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_DF6203979692E25D (selector), INDEX IDX_DF620397A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_registration (id BINARY(16) NOT NULL COMMENT \'(DC2Type:uuid)\', email VARCHAR(180) NOT NULL, expire_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', state VARCHAR(32) NOT NULL, selector VARCHAR(32) NOT NULL, verifier VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', updated_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', UNIQUE INDEX UNIQ_E264DBA59692E25D (selector), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, headers LONGTEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', available_at DATETIME NOT NULL COMMENT \'(DC2Type:datetime_immutable)\', delivered_at DATETIME DEFAULT NULL COMMENT \'(DC2Type:datetime_immutable)\', INDEX IDX_75EA56E0FB7336F0 (queue_name), INDEX IDX_75EA56E0E3BD61CE (available_at), INDEX IDX_75EA56E016BA31DB (delivered_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1C8047505 FOREIGN KEY (camp_date_id) REFERENCES camp_date (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC15AA1164F FOREIGN KEY (payment_method_id) REFERENCES payment_method (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE application_attachment ADD CONSTRAINT FK_EDCE8573E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_attachment ADD CONSTRAINT FK_EDCE857F300DF07 FOREIGN KEY (application_camper_id) REFERENCES application_camper (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_camper ADD CONSTRAINT FK_10FF46133E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_contact ADD CONSTRAINT FK_A7DCE30B3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_form_field_value ADD CONSTRAINT FK_922E73113E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_form_field_value ADD CONSTRAINT FK_922E7311F300DF07 FOREIGN KEY (application_camper_id) REFERENCES application_camper (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_payment ADD CONSTRAINT FK_8696813E2AE7DEAB FOREIGN KEY (application_payment_state_config_id) REFERENCES application_payment_state_config (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_payment ADD CONSTRAINT FK_8696813E3E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_purchasable_item ADD CONSTRAINT FK_6343508D16B4E87 FOREIGN KEY (purchasable_item_id) REFERENCES purchasable_item (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE application_purchasable_item ADD CONSTRAINT FK_63435083E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_purchasable_item_instance ADD CONSTRAINT FK_907069E3F300DF07 FOREIGN KEY (application_camper_id) REFERENCES application_camper (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_purchasable_item_instance ADD CONSTRAINT FK_907069E3EBD7A28D FOREIGN KEY (application_purchasable_item_id) REFERENCES application_purchasable_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_trip_location_path ADD CONSTRAINT FK_B334885F300DF07 FOREIGN KEY (application_camper_id) REFERENCES application_camper (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attachment_config_file_extension ADD CONSTRAINT FK_50153545520354A0 FOREIGN KEY (attachment_config_id) REFERENCES attachment_config (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE attachment_config_file_extension ADD CONSTRAINT FK_50153545AB8C6E61 FOREIGN KEY (file_extension_id) REFERENCES file_extension (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp ADD CONSTRAINT FK_C1944230B10A86AE FOREIGN KEY (camp_category_id) REFERENCES camp_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE camp_category ADD CONSTRAINT FK_AC36C6DD727ACA70 FOREIGN KEY (parent_id) REFERENCES camp_category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE camp_date ADD CONSTRAINT FK_4F7C997277075ABB FOREIGN KEY (camp_id) REFERENCES camp (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date ADD CONSTRAINT FK_4F7C997244018E7E FOREIGN KEY (discount_config_id) REFERENCES discount_config (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE camp_date ADD CONSTRAINT FK_4F7C997263DD4162 FOREIGN KEY (trip_location_path_there_id) REFERENCES trip_location_path (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE camp_date ADD CONSTRAINT FK_4F7C99728B465358 FOREIGN KEY (trip_location_path_back_id) REFERENCES trip_location_path (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE camp_date_attachment_config ADD CONSTRAINT FK_BCCB6E1CC8047505 FOREIGN KEY (camp_date_id) REFERENCES camp_date (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_attachment_config ADD CONSTRAINT FK_BCCB6E1C520354A0 FOREIGN KEY (attachment_config_id) REFERENCES attachment_config (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_form_field ADD CONSTRAINT FK_C623B972C8047505 FOREIGN KEY (camp_date_id) REFERENCES camp_date (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_form_field ADD CONSTRAINT FK_C623B972F50D82F4 FOREIGN KEY (form_field_id) REFERENCES form_field (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_purchasable_item ADD CONSTRAINT FK_7FCDDE3CC8047505 FOREIGN KEY (camp_date_id) REFERENCES camp_date (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_purchasable_item ADD CONSTRAINT FK_7FCDDE3CD16B4E87 FOREIGN KEY (purchasable_item_id) REFERENCES purchasable_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_user ADD CONSTRAINT FK_B9E6792DC8047505 FOREIGN KEY (camp_date_id) REFERENCES camp_date (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_date_user ADD CONSTRAINT FK_B9E6792DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camp_image ADD CONSTRAINT FK_CB036EC377075ABB FOREIGN KEY (camp_id) REFERENCES camp (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE camper ADD CONSTRAINT FK_A0CC4AD6A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE permission ADD CONSTRAINT FK_E04992AAB6C0CF1 FOREIGN KEY (permission_group_id) REFERENCES permission_group (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE purchasable_item_variant ADD CONSTRAINT FK_83EA40A7D16B4E87 FOREIGN KEY (purchasable_item_id) REFERENCES purchasable_item (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE purchasable_item_variant_value ADD CONSTRAINT FK_9114C932AD0CA35 FOREIGN KEY (purchasable_item_variant_id) REFERENCES purchasable_item_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE role_permission ADD CONSTRAINT FK_6F7DF886FED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trip_location ADD CONSTRAINT FK_F6CFBADB559CC42E FOREIGN KEY (trip_location_path_id) REFERENCES trip_location_path (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_password_change ADD CONSTRAINT FK_DF620397A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1C8047505');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1A76ED395');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC15AA1164F');
        $this->addSql('ALTER TABLE application_attachment DROP FOREIGN KEY FK_EDCE8573E030ACD');
        $this->addSql('ALTER TABLE application_attachment DROP FOREIGN KEY FK_EDCE857F300DF07');
        $this->addSql('ALTER TABLE application_camper DROP FOREIGN KEY FK_10FF46133E030ACD');
        $this->addSql('ALTER TABLE application_contact DROP FOREIGN KEY FK_A7DCE30B3E030ACD');
        $this->addSql('ALTER TABLE application_form_field_value DROP FOREIGN KEY FK_922E73113E030ACD');
        $this->addSql('ALTER TABLE application_form_field_value DROP FOREIGN KEY FK_922E7311F300DF07');
        $this->addSql('ALTER TABLE application_payment DROP FOREIGN KEY FK_8696813E2AE7DEAB');
        $this->addSql('ALTER TABLE application_payment DROP FOREIGN KEY FK_8696813E3E030ACD');
        $this->addSql('ALTER TABLE application_purchasable_item DROP FOREIGN KEY FK_6343508D16B4E87');
        $this->addSql('ALTER TABLE application_purchasable_item DROP FOREIGN KEY FK_63435083E030ACD');
        $this->addSql('ALTER TABLE application_purchasable_item_instance DROP FOREIGN KEY FK_907069E3F300DF07');
        $this->addSql('ALTER TABLE application_purchasable_item_instance DROP FOREIGN KEY FK_907069E3EBD7A28D');
        $this->addSql('ALTER TABLE application_trip_location_path DROP FOREIGN KEY FK_B334885F300DF07');
        $this->addSql('ALTER TABLE attachment_config_file_extension DROP FOREIGN KEY FK_50153545520354A0');
        $this->addSql('ALTER TABLE attachment_config_file_extension DROP FOREIGN KEY FK_50153545AB8C6E61');
        $this->addSql('ALTER TABLE camp DROP FOREIGN KEY FK_C1944230B10A86AE');
        $this->addSql('ALTER TABLE camp_category DROP FOREIGN KEY FK_AC36C6DD727ACA70');
        $this->addSql('ALTER TABLE camp_date DROP FOREIGN KEY FK_4F7C997277075ABB');
        $this->addSql('ALTER TABLE camp_date DROP FOREIGN KEY FK_4F7C997244018E7E');
        $this->addSql('ALTER TABLE camp_date DROP FOREIGN KEY FK_4F7C997263DD4162');
        $this->addSql('ALTER TABLE camp_date DROP FOREIGN KEY FK_4F7C99728B465358');
        $this->addSql('ALTER TABLE camp_date_attachment_config DROP FOREIGN KEY FK_BCCB6E1CC8047505');
        $this->addSql('ALTER TABLE camp_date_attachment_config DROP FOREIGN KEY FK_BCCB6E1C520354A0');
        $this->addSql('ALTER TABLE camp_date_form_field DROP FOREIGN KEY FK_C623B972C8047505');
        $this->addSql('ALTER TABLE camp_date_form_field DROP FOREIGN KEY FK_C623B972F50D82F4');
        $this->addSql('ALTER TABLE camp_date_purchasable_item DROP FOREIGN KEY FK_7FCDDE3CC8047505');
        $this->addSql('ALTER TABLE camp_date_purchasable_item DROP FOREIGN KEY FK_7FCDDE3CD16B4E87');
        $this->addSql('ALTER TABLE camp_date_user DROP FOREIGN KEY FK_B9E6792DC8047505');
        $this->addSql('ALTER TABLE camp_date_user DROP FOREIGN KEY FK_B9E6792DA76ED395');
        $this->addSql('ALTER TABLE camp_image DROP FOREIGN KEY FK_CB036EC377075ABB');
        $this->addSql('ALTER TABLE camper DROP FOREIGN KEY FK_A0CC4AD6A76ED395');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638A76ED395');
        $this->addSql('ALTER TABLE permission DROP FOREIGN KEY FK_E04992AAB6C0CF1');
        $this->addSql('ALTER TABLE purchasable_item_variant DROP FOREIGN KEY FK_83EA40A7D16B4E87');
        $this->addSql('ALTER TABLE purchasable_item_variant_value DROP FOREIGN KEY FK_9114C932AD0CA35');
        $this->addSql('ALTER TABLE role_permission DROP FOREIGN KEY FK_6F7DF886D60322AC');
        $this->addSql('ALTER TABLE role_permission DROP FOREIGN KEY FK_6F7DF886FED90CCA');
        $this->addSql('ALTER TABLE trip_location DROP FOREIGN KEY FK_F6CFBADB559CC42E');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649D60322AC');
        $this->addSql('ALTER TABLE user_password_change DROP FOREIGN KEY FK_DF620397A76ED395');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE application_attachment');
        $this->addSql('DROP TABLE application_camper');
        $this->addSql('DROP TABLE application_contact');
        $this->addSql('DROP TABLE application_form_field_value');
        $this->addSql('DROP TABLE application_payment');
        $this->addSql('DROP TABLE application_payment_state_config');
        $this->addSql('DROP TABLE application_purchasable_item');
        $this->addSql('DROP TABLE application_purchasable_item_instance');
        $this->addSql('DROP TABLE application_trip_location_path');
        $this->addSql('DROP TABLE attachment_config');
        $this->addSql('DROP TABLE attachment_config_file_extension');
        $this->addSql('DROP TABLE camp');
        $this->addSql('DROP TABLE camp_category');
        $this->addSql('DROP TABLE camp_date');
        $this->addSql('DROP TABLE camp_date_attachment_config');
        $this->addSql('DROP TABLE camp_date_form_field');
        $this->addSql('DROP TABLE camp_date_purchasable_item');
        $this->addSql('DROP TABLE camp_date_user');
        $this->addSql('DROP TABLE camp_image');
        $this->addSql('DROP TABLE camper');
        $this->addSql('DROP TABLE contact');
        $this->addSql('DROP TABLE discount_config');
        $this->addSql('DROP TABLE file_extension');
        $this->addSql('DROP TABLE form_field');
        $this->addSql('DROP TABLE payment_method');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE permission_group');
        $this->addSql('DROP TABLE purchasable_item');
        $this->addSql('DROP TABLE purchasable_item_variant');
        $this->addSql('DROP TABLE purchasable_item_variant_value');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_permission');
        $this->addSql('DROP TABLE trip_location');
        $this->addSql('DROP TABLE trip_location_path');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_password_change');
        $this->addSql('DROP TABLE user_registration');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
