# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.menu_theme: '_fragment/_menu_theme/_main.html.twig'
    app.tax: 21 # percent

    # Directories & paths
    app.camp_image_directory: 'files/dynamic/camp'
    app.no_camp_image_path: 'files/static/placeholder.jpg'
    app.purchasable_item_image_directory: 'files/dynamic/purchasable-item'
    app.no_purchasable_item_image_path: 'files/static/placeholder.jpg'
    app.application_attachment_directory: 'files/dynamic/application-attachment'

    # Mailer
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_format: 'd.m.Y'
    app.date_time_format: 'd.m.Y H:i'
    app.currency: 'CZK'
    app.locales: 'cs' # Enabled locales (languages) divided by "|"
    app.locale_names:
        cs: 'Česky'

    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1 # e.g. +420 123 456 789
    app.national_identifier: true
    app.eu_business_data: true
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'

    # Security
    app.max_active_registrations_per_email: 5
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 5
    app.password_change_lifespan: '1 hour'
    app.social_login_services: 'facebook|google'
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

        google:
            - 'https://www.googleapis.com/auth/userinfo.profile'
            - 'https://www.googleapis.com/auth/userinfo.email'

    # Cookies
    app.cookie_lifespan_locale: '1 year'

    # Applications
    app.sale_camper_recurring: true
    app.sale_camper_siblings: true
    app.contact_email_mandatory: false
    app.contact_phone_number_mandatory: true
    app.application_simple_id_length: 6
    app.application_simple_id_characters: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'

    # Validation
    app.national_identifier_regex: '#^(\d\d)(\d\d)(\d\d)( |/)?(\d\d\d)(\d?)$#'
    app.eu_cin_regex: '#^\d{8}$#'
    app.eu_vat_id_regex: '#^(((CZ)[0-9]{8,10})|((SK)[0-9]{10}))$#'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire:      true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Library/'
            - '../src/Model/Attribute/'
            - '../src/Model/Entity/'
            - '../src/Model/Enum/'
            - '../src/Model/Event/'
            - '../src/Model/Library/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Menu\Factory\MenuTypeFactoryInterface:
            tags: [ 'app.menu_factory' ]

        App\Service\Data\Transfer\DataTransferInterface:
            tags: [ 'app.data_transfer' ]

    Symfony\Bridge\Monolog\Processor\TokenProcessor:
        autoconfigure: false
        tags:
            - { name: 'monolog.processor', channel: 'model' }

    App\Service\Logger\ModelLogger:
        arguments:
            $logger: '@monolog.logger.model'

    App\Service\Security\Authentication\SocialLoginRedirectResponseFactory:
        arguments:
            $scopes: '%app.social_login_scopes%'

    App\Service\Security\Authentication\SocialAuthenticator:
        arguments:
            $services: '%app.social_login_services%'

    App\Model\Service\UserRegistration\UserRegistrationFactory:
        arguments:
            $maxActiveRegistrationsPerEmail: '%app.max_active_registrations_per_email%'
            $registrationLifespan: '%app.registration_lifespan%'

    App\Model\Service\UserPasswordChange\UserPasswordChangeFactory:
        arguments:
            $maxActivePasswordChangesPerUser: '%app.max_active_password_changes_per_user%'
            $passwordChangeLifespan: '%app.password_change_lifespan%'

    App\Model\Service\CampImage\CampImageFactory:
        arguments:
            $campImageUploadDirectory: '%kernel.project_dir%/public/%app.camp_image_directory%'

    App\Model\Service\CampImage\CampImageFilesystem:
        arguments:
            $kernelProjectDirectory: '%kernel.project_dir%'
            $noImagePath: '%app.no_camp_image_path%'
            $campImageDirectory: '%app.camp_image_directory%'

    App\Model\Service\PurchasableItem\PurchasableItemImageFilesystem:
        arguments:
            $kernelProjectDirectory: '%kernel.project_dir%'
            $noImagePath: '%app.no_purchasable_item_image_path%'
            $purchasableItemImageDirectory: '%app.purchasable_item_image_directory%'

    App\Model\Service\ApplicationCamper\ApplicationCamperDataFactory:
        arguments:
            $isNationalIdentifierEnabled: '%app.national_identifier%'
            $currency: '%app.currency%'

    App\Model\Service\Application\ApplicationStepOneDataFactory:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'
            $isNationalIdentifierEnabled: '%app.national_identifier%'
            $currency: '%app.currency%'
            $tax: '%app.tax%'

    App\Model\Service\Application\ApplicationFactory:
        arguments:
            $simpleIdCharacters: '%app.application_simple_id_characters%'
            $simpleIdLength: '%app.application_simple_id_length%'

    App\Model\Service\ApplicationAttachment\ApplicationAttachmentFilesystem:
        arguments:
            $applicationAttachmentDirectory: '%app.application_attachment_directory%'
            $kernelProjectDirectory: '%kernel.project_dir%'

    App\Model\Service\Contact\ContactDataFactory:
        arguments:
            $isEmailMandatory: '%app.contact_email_mandatory%'
            $isPhoneNumberMandatory: '%app.contact_phone_number_mandatory%'

    App\Service\Form\Extension\CountryTypeDefaultsExtension:
        arguments:
            $preferredCountries: '%app.preferred_country_choices%'

    App\Service\Form\Extension\PhoneNumberTypeDefaultsExtension:
        arguments:
            $phoneNumberDefaultLocale: '%app.phone_number_default_locale%'
            $phoneNumberFormat: '%app.phone_number_format%'

    App\Service\Form\Extension\MoneyTypeDefaultsExtension:
        arguments:
            $currency: '%app.currency%'

    App\Service\Form\Type\Admin\DiscountRecurringCamperConfigType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\DiscountSiblingConfigType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\CampDateType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\TripLocationType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\PurchasableItemType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\User\BillingType:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'

    App\Service\Form\Type\User\CamperType:
        arguments:
            $isNationalIdentifierEnabled: '%app.national_identifier%'

    App\Service\Form\Type\User\ApplicationStepOneType:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'

    App\Service\Menu\Renderer\MenuTypeRenderer:
        arguments:
            $menuTheme: '%app.menu_theme%'

    App\Service\Menu\Factory\LocaleSwitchMenuTypeFactory:
        arguments:
            $locales: '%app.locales%'
            $localeNames: '%app.locale_names%'

    App\Service\Translation\LocaleGuesser:
        arguments:
            $locales: '%app.locales%'
            $defaultLocale: '%kernel.default_locale%'

    App\Service\Translation\LocaleRedirectResponseFactory:
        arguments:
            $locales: '%app.locales%'

    App\Service\EventSubscriber\LocaleCookieSubscriber:
        arguments:
            $locales: '%app.locales%'
            $cookieLifespan: '%app.cookie_lifespan_locale%'

    App\Service\Mailer\UserRegistrationMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'
            $dateTimeFormat: '%app.date_time_format%'

    App\Service\Mailer\UserPasswordChangeMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'
            $dateTimeFormat: '%app.date_time_format%'

    App\Service\Data\Transfer\User\BillingDataTransfer:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'

    App\Service\Data\Transfer\User\CamperDataTransfer:
        arguments:
            $isNationalIdentifierEnabled: '%app.national_identifier%'

    App\Service\Validator\NationalIdentifierValidator:
        arguments:
            $nationalIdentifierRegex: '%app.national_identifier_regex%'

    App\Service\Validator\EuCinValidator:
        arguments:
            $euCinRegex: '%app.eu_cin_regex%'

    App\Service\Validator\EuVatIdValidator:
        arguments:
            $euVatIdRegex: '%app.eu_vat_id_regex%'