services:
    # Breadcrumbs
    App\Menu\Breadcrumbs\Admin\ProfileBreadcrumbsInterface:
        alias: App\Menu\Breadcrumbs\Admin\ProfileBreadcrumbs
        public: true

    App\Menu\Breadcrumbs\User\LoginBreadcrumbsInterface:
        alias: App\Menu\Breadcrumbs\User\LoginBreadcrumbs
        public: true

    # Menu
    App\Menu\Registry\MenuTypeRegistryInterface:
        alias: App\Menu\Registry\MenuTypeRegistry
        public: true

    App\Menu\Renderer\MenuTypeRendererInterface:
        alias: App\Menu\Renderer\MenuTypeRenderer
        public: true

    # Repository
    App\Repository\UserRepositoryInterface:
        alias: App\Repository\UserRepository
        public: true

    # Search
    App\Search\DataStructure\GraphSearchInterface:
        alias: App\Search\DataStructure\GraphSearch
        public: true

    App\Search\Paginator\PaginatorMenuFactoryInterface:
        alias: App\Search\Paginator\PaginatorMenuFactory
        public: true

    # Service
    App\Service\RouteNamerInterface:
        alias: App\Service\RouteNamer
        public: true

    # Translation
    App\Translation\LocaleGuesserInterface:
        alias: App\Translation\LocaleGuesser
        public: true

    App\Translation\LocaleRedirectResponseFactoryInterface:
        alias: App\Translation\LocaleRedirectResponseFactory
        public: true