services:
    App\Search\DataStructure\GraphSearchInterface:
        alias: App\Search\DataStructure\GraphSearch
        public: true

    App\Search\Menu\MenuSearchInterface:
        alias: App\Search\Menu\MenuSearch
        public: true

    App\Menu\Registry\MenuTypeRegistryInterface:
        alias: App\Menu\Registry\MenuTypeRegistry
        public: true