parameters:
    app.menu_theme: '_fragment/_menu_theme/_test.html.twig'

    # Directories
    app.camp_image_directory: 'img/dynamic/camp'
    app.no_camp_image_path: 'img/static/camp/placeholder.jpg'
    app.purchasable_item_image_directory: 'img/dynamic/purchasable-item'
    app.no_purchasable_item_image_path: 'img/static/placeholder.jpg'

    # Mailer
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_format: 'd. m. Y'
    app.date_time_format: 'd. m. Y H:i:s'
    app.currency: 'CZK'
    app.locales: 'en|cs|de'
    app.locale_names:
        en: 'English'
        cs: 'Čeština'
        de: 'Deutsch'

    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1
    app.national_identifier: true
    app.eu_business_data: true
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'
        - 'DE'

    # Security
    app.max_active_registrations_per_email: 2
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 2
    app.password_change_lifespan: '1 hour'
    app.social_login_services: 'facebook'
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

    # Cookies
    app.cookie_lifespan_locale: '1 year'

    # Applications
    app.sale_camper_recurring: true
    app.sale_camper_siblings: true
    app.contact_email_mandatory: false
    app.contact_phone_number_mandatory: false

    # Validation
    app.national_identifier_regex: '#^\s*(\d\d)(\d\d)(\d\d)[ /]*(\d\d\d)(\d?)\s*$#'
    app.eu_cin_regex: '#^\d{8}$#'
    app.eu_vat_id_regex: '#^(((CZ)[0-9]{8,10})|((SK)[0-9]{10}))$#'

services:
    # Interfaces
    Symfony\Contracts\Translation\TranslatorInterface:
        class: App\Tests\Service\Translation\TranslatorMock

    Symfony\Component\Mailer\MailerInterface:
        class: App\Tests\Service\Mailer\MailerMock

    App\Service\Security\Token\TokenSplitterInterface:
        class: App\Tests\Service\Security\Token\TokenSplitterMock

    # Classes
    App\Service\Security\Token\TokenSplitter:
        public: true