# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.menu_theme: '_fragment/_menu_theme/_main.html.twig'

    # Internationalization
    app.locales: 'cs' # Enabled locales (languages) divided by "|"
    app.locale_names:
        en: 'English'
        cs: 'Česky'

    # Cookies
    app.cookie_lifespan_locale: '1 year'

    # Route translation keys
    app.route_trans_keys:
        admin_home: 'route.admin.home'
        admin_profile: 'route.admin.profile'

        user_home: 'route.user.home'
        user_login: 'route.user.login'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire:      true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/DataStructure/'
            - '../src/Form/DTO/'
            - '../src/Menu/Type/'
            - '../src/Menu/Registry/MenuTypeRegistryRecord.php'
            - '../src/Search/Paginator/Paginator.php'
            - '../src/Kernel.php'

    _instanceof:
        App\Menu\Factory\MenuTypeFactoryInterface:
            tags: ['app.menu_factory']

    App\Service\RouteNamer:
        arguments:
            $routeTransKeys: '%app.route_trans_keys%'

    App\Menu\Renderer\MenuTypeRenderer:
        arguments:
            $menuTheme: '%app.menu_theme%'

    App\Menu\Factory\LocaleSwitchMenuTypeFactory:
        arguments:
            $locales: '%app.locales%'
            $localeNames: '%app.locale_names%'

    App\Translation\LocaleGuesser:
        arguments:
            $locales: '%app.locales%'
            $defaultLocale: '%kernel.default_locale%'

    App\Translation\LocaleRedirectResponseFactory:
        arguments:
            $locales: '%app.locales%'

    App\EventDispatcher\EventSubscriber\LocaleCookieSubscriber:
        arguments:
            $locales: '%app.locales%'
            $cookieLifespan: '%app.cookie_lifespan_locale%'