parameters:
    app.menu_theme: '_fragment/_menu_theme/_test.html.twig'
    app.tax: 21 # percent

    # Company info
    app.company_name: 'Camp'
    app.company_structure: 'LLC'
    app.company_cin: '12345678'
    app.company_vat_id: 'CZ12345678'
    app.company_extra_business_info: 'Some extra business related info.'
    app.company_bank_account: '000000-1234567890/0600'
    app.company_phone_number: '+420 123 456 789'
    app.company_address_street: 'Green Leaf 123'
    app.company_address_town: 'Prague'
    app.company_address_zip: '100 00'
    app.company_address_country: 'Czech Republic'

    # Directories
    app.public_file_path_prefix: '/'
    app.company_logo_path: 'files/static/company_logo.png'
    app.camp_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.camp_image_directory: 'files/dynamic/camp'
    app.no_camp_image_path: 'files/static/placeholder.jpg'
    app.purchasable_item_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.purchasable_item_image_directory: 'files/dynamic/purchasable-item'
    app.no_purchasable_item_image_path: 'files/static/placeholder.jpg'
    app.user_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.user_image_directory: 'files/dynamic/user'
    app.no_user_image_path: 'files/static/user_placeholder.png'
    app.application_attachment_directory: 'files/dynamic/application-attachment'
    app.application_invoice_directory: 'files/dynamic/application-invoice'

    # Mailer
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_format: 'd. m. Y'
    app.date_time_format: 'd.m.Y H:i'
    app.currency: 'CZK'
    app.locales: 'en|cs|de'
    app.locale_names:
        en: 'English'
        cs: 'Čeština'
        de: 'Deutsch'

    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1
    app.national_identifier: true
    app.eu_business_data: true
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'
        - 'DE'

    # Security
    app.max_active_registrations_per_email: 2
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 2
    app.password_change_lifespan: '1 hour'
    app.social_login_services: 'facebook'
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

    # Cookies
    app.cookie_lifespan_locale: '1 year'
    app.cookie_lifespan_application_draft: '1 year'
    app.cookie_prefix_application_draft: 'application_draft_'

    # Session
    app.last_completed_application_id_session_key: 'last_completed_application_id'

    # Applications
    app.application_purchasable_items_individual: false
    app.sale_camper_recurring: true
    app.sale_camper_siblings: true
    app.contact_email_mandatory: false
    app.contact_phone_number_mandatory: false
    app.application_invoice_number_length: 10
    app.application_simple_id_length: 6
    app.application_simple_id_characters: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    app.enabled_payment_methods: ['card', 'transfer', 'invoice']
    app.completed_application_lifetime: '14 days'

    # Validation
    app.national_identifier_regex: '#^\s*(\d\d)(\d\d)(\d\d)[ /]*(\d\d\d)(\d?)\s*$#'
    app.eu_cin_regex: '#^\d{8}$#'
    app.eu_vat_id_regex: '#^(((CZ)[0-9]{8,10})|((SK)[0-9]{10}))$#'

services:
    # Interfaces
    Symfony\Contracts\Translation\TranslatorInterface:
        class: App\Tests\Service\Translation\TranslatorMock

    Symfony\Component\Mailer\MailerInterface:
        class: App\Tests\Service\Mailer\MailerMock

    App\Service\Security\Token\TokenSplitterInterface:
        class: App\Tests\Service\Security\Token\TokenSplitterMock

    # Classes
    App\Service\Security\Token\TokenSplitter:
        public: true