# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.menu_theme: '_fragment/_menu_theme/_main.html.twig'
    app.tax: 21 # percent

    # Company info
    app.company_name: 'Tábor'
    app.company_structure: 's.r.o.'
    app.company_cin: '12345678'
    app.company_vat_id: 'CZ12345678'
    app.company_extra_business_info: 'Zapsáno v OR u MS v Praze.'
    app.company_bank_account: '000000-1234567890/0600'
    app.company_phone_number: '+420 123 456 789'
    app.company_address_street: 'Dlouhá 123'
    app.company_address_town: 'Praha 1'
    app.company_address_zip: '100 00'
    app.company_address_country: 'Česko'

    # Directories & paths
    app.public_file_path_prefix: '/'
    app.company_logo_path: 'files/static/company_logo.png'
    app.camp_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.camp_image_directory: 'files/dynamic/camp'
    app.no_camp_image_path: 'files/static/placeholder.jpg'
    app.purchasable_item_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.purchasable_item_image_directory: 'files/dynamic/purchasable-item'
    app.no_purchasable_item_image_path: 'files/static/placeholder.jpg'
    app.user_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.user_image_directory: 'files/dynamic/user'
    app.no_user_image_path: 'files/static/user_placeholder.png'
    app.application_attachment_directory: 'files/dynamic/application-attachment'
    app.application_invoice_directory: 'files/dynamic/application-invoice'

    # Mailer
    app.email: 'contact.us@camp.com'
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_format: 'd.m.Y'
    app.date_time_format: 'd.m.Y H:i'
    app.currency: 'CZK'
    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1 # e.g. +420 123 456 789
    app.national_identifier: true
    app.eu_business_data: true
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'

    # Security
    app.max_active_registrations_per_email: 5
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 5
    app.password_change_lifespan: '1 hour'
    app.social_login_services: [ 'facebook', 'google' ]
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

        google:
            - 'https://www.googleapis.com/auth/userinfo.profile'
            - 'https://www.googleapis.com/auth/userinfo.email'

    # Cookies
    app.cookie_lifespan_application_draft: '1 year'
    app.cookie_prefix_application_draft: 'application_draft_'

    # Session
    app.last_completed_application_id_session_key: 'last_completed_application_id'

    # Applications
    app.application_purchasable_items_individual: true
    app.contact_email_mandatory: false
    app.contact_phone_number_mandatory: true
    app.application_invoice_number_length: 10
    app.application_simple_id_length: 6
    app.application_simple_id_characters: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    app.enabled_payment_methods: [ 'card', 'transfer', 'invoice' ]

    # Validation
    app.national_identifier_regex: '#^(\d\d)(\d\d)(\d\d)( |/)?(\d\d\d)(\d?)$#'
    app.eu_cin_regex: '#^\d{8}$#'
    app.eu_vat_id_regex: '#^(((CZ)[0-9]{8,10})|((SK)[0-9]{10}))$#'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire:      true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Library/'
            - '../src/Model/Attribute/'
            - '../src/Model/Entity/'
            - '../src/Model/Enum/'
            - '../src/Model/Event/'
            - '../src/Model/Exception/'
            - '../src/Model/Library/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Menu\Factory\MenuTypeFactoryInterface:
            tags: [ 'app.menu_factory' ]

        App\Service\Data\Transfer\DataTransferInterface:
            tags: [ 'app.data_transfer' ]

        App\Service\Menu\Breadcrumbs\BreadcrumbInterface:
            tags: [ 'app.breadcrumb' ]

        App\Model\Service\PaymentMethod\OfflineInstructions\OfflineInstructionRendererInterface:
            tags: [ 'app.offline_payment_instruction_renderer' ]

    Symfony\Bridge\Monolog\Processor\TokenProcessor:
        autoconfigure: false
        tags:
            - { name: 'monolog.processor', channel: 'model' }

    App\Model\Service\Application\ApplicationToUserImporter:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'
            $isEmailMandatory: '%app.contact_email_mandatory%'
            $isPhoneNumberMandatory: '%app.contact_phone_number_mandatory%'
            $isNationalIdentifierEnabled: '%app.national_identifier%'

    App\Model\EventSubscriber\User\Application\ApplicationStepThreeUpdateSubscriber:
        arguments:
            $lastCompletedApplicationIdSessionKey: '%app.last_completed_application_id_session_key%'

    App\Model\EventSubscriber\User\Application\ApplicationToUserImportSubscriber:
        arguments:
            $lastCompletedApplicationIdSessionKey: '%app.last_completed_application_id_session_key%'

    App\Model\Service\UserRegistration\UserRegistrationFactory:
        arguments:
            $maxActiveRegistrationsPerEmail: '%app.max_active_registrations_per_email%'
            $registrationLifespan: '%app.registration_lifespan%'

    App\Model\Service\UserPasswordChange\UserPasswordChangeFactory:
        arguments:
            $maxActivePasswordChangesPerUser: '%app.max_active_password_changes_per_user%'
            $passwordChangeLifespan: '%app.password_change_lifespan%'

    App\Model\Service\CampImage\CampImageFilesystem:
        arguments:
            $campImagePublicPathPrefix: '%app.camp_image_public_path_prefix%'
            $noImagePath: '%app.no_camp_image_path%'
            $campImageDirectory: '%app.camp_image_directory%'

    App\Model\Service\PurchasableItem\PurchasableItemImageFilesystem:
        arguments:
            $purchasableItemImagePublicPathPrefix: '%app.purchasable_item_image_public_path_prefix%'
            $noImagePath: '%app.no_purchasable_item_image_path%'
            $purchasableItemImageDirectory: '%app.purchasable_item_image_directory%'

    App\Model\Service\User\UserImageFilesystem:
        arguments:
            $userImagePublicPathPrefix: '%app.user_image_public_path_prefix%'
            $noImagePath: '%app.no_user_image_path%'
            $userImageDirectory: '%app.user_image_directory%'

    App\Model\Service\Application\ApplicationDraftCookieStorage:
        arguments:
            $cookieKeyPrefix: '%app.cookie_prefix_application_draft%'
            $cookieLifespan: '%app.cookie_lifespan_application_draft%'

    App\Model\Service\ApplicationCamper\ApplicationCamperDataFactory:
        arguments:
            $isNationalIdentifierEnabled: '%app.national_identifier%'
            $currency: '%app.currency%'

    App\Model\Service\Application\ApplicationStepOneDataFactory:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'
            $isNationalIdentifierEnabled: '%app.national_identifier%'
            $currency: '%app.currency%'
            $tax: '%app.tax%'

    App\Model\Service\Application\ApplicationFactory:
        arguments:
            $isPurchasableItemsIndividualMode: '%app.application_purchasable_items_individual%'
            $simpleIdCharacters: '%app.application_simple_id_characters%'
            $simpleIdLength: '%app.application_simple_id_length%'

    App\Model\Service\Application\ApplicationInvoiceFilesystem:
        arguments:
            $publicFilePathPrefix: '%app.public_file_path_prefix%'

    App\Model\Service\Application\ApplicationInvoiceNumberFormatter:
        arguments:
            $invoiceNumberLength: '%app.application_invoice_number_length%'

    App\Model\Service\Application\ApplicationCompletedMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'

    App\Model\Service\UserPasswordChange\UserPasswordChangeMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'

    App\Model\Service\UserRegistration\UserRegistrationMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'

    App\Model\Repository\ApplicationRepository:
        arguments:
            $currency: '%app.currency%'
            $lastCompletedApplicationIdSessionKey: '%app.last_completed_application_id_session_key%'

    App\Model\Repository\PaymentMethodRepository:
        arguments:
            $enabledPaymentMethods: '%app.enabled_payment_methods%'

    App\Service\Logger\ModelLogger:
        arguments:
            $logger: '@monolog.logger.model'

    App\Service\Security\Authentication\SocialLoginRedirectResponseFactory:
        arguments:
            $scopes: '%app.social_login_scopes%'

    App\Service\Security\Authentication\SocialAuthenticator:
        arguments:
            $services: '%app.social_login_services%'

    App\Service\Form\Extension\CountryTypeDefaultsExtension:
        arguments:
            $preferredCountries: '%app.preferred_country_choices%'

    App\Service\Form\Extension\PhoneNumberTypeDefaultsExtension:
        arguments:
            $phoneNumberDefaultLocale: '%app.phone_number_default_locale%'
            $phoneNumberFormat: '%app.phone_number_format%'

    App\Service\Form\Extension\MoneyTypeDefaultsExtension:
        arguments:
            $currency: '%app.currency%'

    App\Service\Twig\ImageExtension:
        arguments:
            $publicFilePathPrefix: '%app.public_file_path_prefix%'
            $companyLogoPath: '%app.company_logo_path%'

    App\Service\Twig\ApplicationToUserImportExtension:
        arguments:
            $lastCompletedApplicationIdSessionKey: '%app.last_completed_application_id_session_key%'

    App\Service\Form\Type\Common\BillingType:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'

    App\Service\Form\Type\Common\ContactType:
        arguments:
            $phoneNumberFormat: '%app.phone_number_format%'

    App\Service\Form\Type\Admin\DiscountRecurringCamperConfigType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\DiscountSiblingConfigType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\CampDateType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\TripLocationType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\Admin\PurchasableItemType:
        arguments:
            $tax: '%app.tax%'

    App\Service\Form\Type\User\ApplicationImportToUserCamperType:
        arguments:
            $dateFormat: '%app.date_format%'

    App\Service\Menu\Renderer\MenuTypeRenderer:
        arguments:
            $menuTheme: '%app.menu_theme%'

    App\Service\Routing\RouteNamer:
        arguments:
            $companyName: '%app.company_name%'

    App\Service\Data\Transfer\Common\BillingDataTransfer:
        arguments:
            $isEuBusinessDataEnabled: '%app.eu_business_data%'

    App\Service\Validator\NationalIdentifierValidator:
        arguments:
            $nationalIdentifierRegex: '%app.national_identifier_regex%'

    App\Service\Validator\EuCinValidator:
        arguments:
            $euCinRegex: '%app.eu_cin_regex%'

    App\Service\Validator\EuVatIdValidator:
        arguments:
            $euVatIdRegex: '%app.eu_vat_id_regex%'