parameters:
    app.menu_theme: '_fragment/_menu_theme/_test.html.twig'

    # Mailer
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_time_format: 'd. m. Y H:i:s'
    app.locales: 'en|cs|de'
    app.locale_names:
        en: 'English'
        cs: 'Čeština'
        de: 'Deutsch'
    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1

    # Security
    app.max_active_registrations_per_email: 2
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 2
    app.password_change_lifespan: '1 hour'
    app.social_login_services: 'facebook'
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

    # Cookies
    app.cookie_lifespan_locale: '1 year'

    # Applications
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'
        - 'DE'

    app.autocomplete_insurance_companies:
        - 'VZP, Všeobecná zdravotní pojišťovna ČR'
        - 'VoZP, Vojenská zdravotní pojišťovna ČR'
        - 'ČPZP, Česká průmyslová zdravotní pojišťovna'

services:
    # Interfaces
    Symfony\Contracts\Translation\TranslatorInterface:
        class: App\Tests\Translation\TranslatorMock

    Symfony\Component\Mailer\MailerInterface:
        class: App\Tests\Mailer\MailerMock

    App\Security\Token\TokenSplitterInterface:
        class: App\Tests\Security\Token\TokenSplitterMock

    # Classes
    App\Security\Token\TokenSplitter:
        public: true