# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.menu_theme: '_fragment/_menu_theme/_main.html.twig'

    # Mailer
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_time_format: 'd.m.Y H:i:s'
    app.locales: 'cs' # Enabled locales (languages) divided by "|"
    app.locale_names:
        cs: 'Česky'
    app.billing_countries:
        - 'cs'
        - 'sk'
    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1 # e.g. +420 123 456 789

    # Security
    app.max_active_registrations_per_email: 5
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 5
    app.password_change_lifespan: '1 hour'
    app.social_login_services: 'facebook|google'
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'
        google:
            - 'https://www.googleapis.com/auth/userinfo.profile'
            - 'https://www.googleapis.com/auth/userinfo.email'

    # Cookies
    app.cookie_lifespan_locale: '1 year'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire:      true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Enum/'
            - '../src/DataStructure/'
            - '../src/Form/DataTransfer/Data/'
            - '../src/Menu/Type/'
            - '../src/Security/Authentication/Exception/'
            - '../src/Security/Token/TokenSplit.php'
            - '../src/Security/Registration/UserRegistrationResult.php'
            - '../src/Security/PasswordChange/UserPasswordChangeResult.php'
            - '../src/Search/Paginator/'
            - '../src/Kernel.php'

    _instanceof:
        App\Menu\Factory\MenuTypeFactoryInterface:
            tags: ['app.menu_factory']

        App\Form\DataTransfer\Transfer\DataTransferInterface:
            tags: [ 'app.data_transfer' ]

    App\Security\Authentication\SocialLoginRedirectResponseFactory:
        arguments:
            $scopes: '%app.social_login_scopes%'

    App\Security\Authentication\SocialAuthenticator:
        arguments:
            $services: '%app.social_login_services%'

    App\Security\Registration\UserRegistrationFactory:
        arguments:
            $maxActiveRegistrationsPerEmail: '%app.max_active_registrations_per_email%'
            $registrationLifespan: '%app.registration_lifespan%'

    App\Security\PasswordChange\UserPasswordChangeFactory:
        arguments:
            $maxActivePasswordChangesPerUser: '%app.max_active_password_changes_per_user%'
            $passwordChangeLifespan: '%app.password_change_lifespan%'

    App\Menu\Renderer\MenuTypeRenderer:
        arguments:
            $menuTheme: '%app.menu_theme%'

    App\Menu\Factory\LocaleSwitchMenuTypeFactory:
        arguments:
            $locales: '%app.locales%'
            $localeNames: '%app.locale_names%'

    App\Translation\LocaleGuesser:
        arguments:
            $locales: '%app.locales%'
            $defaultLocale: '%kernel.default_locale%'

    App\Translation\LocaleRedirectResponseFactory:
        arguments:
            $locales: '%app.locales%'

    App\EventDispatcher\EventSubscriber\LocaleCookieSubscriber:
        arguments:
            $locales: '%app.locales%'
            $cookieLifespan: '%app.cookie_lifespan_locale%'

    App\Mailer\UserRegistrationMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'
            $dateTimeFormat: '%app.date_time_format%'

    App\Mailer\UserPasswordChangeMailer:
        arguments:
            $emailFrom: '%app.email_no_reply%'
            $dateTimeFormat: '%app.date_time_format%'

    App\Repository\ContactRepository:
        arguments:
            $phoneNumberDefaultLocale: '%app.phone_number_default_locale%'

    App\Form\Type\User\BillingType:
        arguments:
            $billingCountries: '%app.billing_countries%'

    App\Form\Type\User\ContactType:
        arguments:
            $phoneNumberDefaultLocale: '%app.phone_number_default_locale%'
            $phoneNumberFormat: '%app.phone_number_format%'