parameters:
    app.menu_theme: '_fragment/_menu_theme/_main.html.twig'
    app.tax: 21 # percent

    # Company info
    app.company_name: 'Tábor'
    app.company_structure: 's.r.o.'
    app.company_cin: '12345678'
    app.company_vat_id: 'CZ12345678'
    app.company_extra_business_info: 'Zapsáno v OR u MS v Praze.'
    app.company_bank_account: '000000-1234567890/0600'
    app.company_phone_number: '+420 123 456 789'
    app.company_address_street: 'Dlouhá 123'
    app.company_address_town: 'Praha 1'
    app.company_address_zip: '100 00'
    app.company_address_country: 'Česko'
    app.company_social_media:
        facebook:
            name: 'Facebook'
            icon: 'fab fa-facebook-f'
            link: 'https://facebook.com'

        instagram:
            name: 'Instagram'
            icon: 'fab fa-instagram'
            link: 'https://instagram.com'

        tiktok:
            name: 'TikTok'
            icon: 'fab fa-tiktok'
            link: 'https://tiktok.com'

    # Directories & paths
    app.public_file_path_prefix: '/'
    app.company_logo_path: 'files/static/company_logo.png'
    app.camp_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.camp_image_directory: 'files/dynamic/camp'
    app.no_camp_image_path: 'files/static/placeholder.jpg'
    app.purchasable_item_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.purchasable_item_image_directory: 'files/dynamic/purchasable-item'
    app.no_purchasable_item_image_path: 'files/static/placeholder.jpg'
    app.user_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.user_image_directory: 'files/dynamic/user'
    app.no_user_image_path: 'files/static/user_placeholder.png'
    app.gallery_image_public_path_prefix: '%app.public_file_path_prefix%'
    app.gallery_image_directory: 'files/dynamic/gallery-image'
    app.no_gallery_image_path: 'files/static/placeholder.jpg'
    app.application_attachment_directory: 'files/dynamic/application-attachment'
    app.application_invoice_directory: 'files/dynamic/application-invoice'
    app.application_admin_attachment_directory: 'files/dynamic/application-admin-attachment'
    app.downloadable_file_public_path_prefix: '%app.public_file_path_prefix%'
    app.downloadable_file_directory: 'files/dynamic/downloadable-file'

    # Mailer
    app.email: 'contact.us@camp.com'
    app.email_no_reply: 'noreply@camp.com'

    # Internationalization
    app.date_format: 'd.m.Y'
    app.date_time_format: 'd.m.Y H:i'
    app.currency: 'CZK'
    app.phone_number_default_locale: 'CZ'
    app.phone_number_format: 1 # e.g. +420 123 456 789
    app.national_identifier: true
    app.eu_business_data: true
    app.preferred_country_choices:
        - 'CZ'
        - 'SK'

    # Security
    app.max_active_registrations_per_email: 5
    app.registration_lifespan: '1 hour'
    app.max_active_password_changes_per_user: 5
    app.password_change_lifespan: '1 hour'
    app.social_login_services: [ 'facebook', 'google' ]
    app.social_login_scopes:
        facebook:
            - 'public_profile'
            - 'email'

        google:
            - 'https://www.googleapis.com/auth/userinfo.profile'
            - 'https://www.googleapis.com/auth/userinfo.email'

    # GET parameters
    app.get_param_set_theme: '_set_theme'

    # POST parameters
    app.post_param_cookie_consent_grant_all: '_cookie_consent_grant_all'
    app.post_param_cookie_consent_deny_all: '_cookie_consent_deny_all'
    app.post_param_cookie_consent_grant_preferences: '_cookie_consent_grant_preferences'
    app.post_param_cookie_consent_preferences: '_cookie_consent_preferences'

    # Cookie consents
    app.enabled_cookie_consents:
        analytics: true
        personalization: true
        marketing: true
        crm: true
        remarketing: true

    # Cookies
    app.cookie_lifespan_application_draft: '1 year'
    app.cookie_prefix_application_draft: 'application_draft_'
    app.cookie_name_visitor_id: 'visitor_id'
    app.cookie_lifespan_theme: '1 year'
    app.cookie_name_theme: 'theme'
    app.cookie_lifespan_consents: '6 months'
    app.cookie_name_consents: 'cookie_consents'

    # Session
    app.last_completed_application_id_session_key: 'last_completed_application_id'

    # Applications
    app.application_purchasable_items_individual: true
    app.contact_email_mandatory: false
    app.contact_phone_number_mandatory: true
    app.application_invoice_number_length: 10
    app.application_simple_id_length: 6
    app.application_simple_id_characters: '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'
    app.enabled_payment_methods: [ 'card', 'transfer', 'invoice' ]

    # Home page
    app.home_max_number_of_featured_guides: 64
    app.home_max_number_of_featured_camps: 64
    app.home_number_of_blog_posts: 4

    # Validation
    app.national_identifier_regex: '#^(\d\d)(\d\d)(\d\d)( |/)?(\d\d\d)(\d?)$#'
    app.eu_cin_regex: '#^\d{8}$#'
    app.eu_vat_id_regex: '#^(((CZ)[0-9]{8,10})|((SK)[0-9]{10}))$#'

    # UI
    app.themes: [ 'light', 'dark' ]

services:
    # default configuration for services in *this* file
    _defaults:
        autowire:      true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/Library/'
            - '../src/Model/Attribute/'
            - '../src/Model/Entity/'
            - '../src/Model/Enum/'
            - '../src/Model/Event/'
            - '../src/Model/Exception/'
            - '../src/Model/Library/'
            - '../src/Kernel.php'

    _instanceof:
        App\Service\Menu\Factory\MenuTypeFactoryInterface:
            tags: [ 'app.menu_factory' ]

        App\Service\Data\Transfer\DataTransferInterface:
            tags: [ 'app.data_transfer' ]

        App\Service\Menu\Breadcrumbs\BreadcrumbInterface:
            tags: [ 'app.breadcrumb' ]

        App\Model\Service\PaymentMethod\OfflineInstructions\OfflineInstructionRendererInterface:
            tags: [ 'app.offline_payment_instruction_renderer' ]

    Symfony\Bridge\Monolog\Processor\TokenProcessor:
        autoconfigure: false
        tags:
            - { name: 'monolog.processor', channel: 'model' }
